### ISSUE TITLE
Missing hydra/defaults

### ISSUE THREAD

**Issue by g3956** [szymanowiczs/splatter-image#3]
Thank you for your brilliant work.

When I run `python train_network.py +dataset=[hydrants]`, I encounter a bug `In 'default_config': Could not find 'hydra/defaults'`.
I checked the configs folder and I found the file is missing in the repository.

**Comment by LaFeuilleMorte** [comment]
> Thank you for your brilliant work.
> 
> When I run `python train_network.py +dataset=[hydrants]`, I encounter a bug `In 'default_config': Could not find 'hydra/defaults'`. I checked the configs folder and I found the file is missing in the repository.

same issue.

**Comment by 13253318778** [comment]
Mee too  . I also encounter the bug. So, I beg for your help, please help me with the help of friends who have solved this problem, thank you very much!
The problem is：
In 'default_config': Could not find 'hydra/defaults'

Available options in 'hydra':
        config
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file://G:\worksplace\splatter-image\configs
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by szymanowiczs** [comment]
Hi - thanks for highlighting, I made an update which should resolve the issue. Let me know if it persists.

**Comment by 13253318778** [comment]
> Hi - thanks for highlighting, I made an update which should resolve the issue. Let me know if it persists.

Yeah，I solved this problem and thank you so much for your help and for your outstanding work. My best wish to you.

**Comment by Pluteapple** [comment]
> > Hi - thanks for highlighting, I made an update which should resolve the issue. Let me know if it persists.
> 
> Yeah，I solved this problem and thank you so much for your help and for your outstanding work. My best wish to you.

Hello, I am still encountering this error while executing this step. Could you please tell me how you resolved it? Also, could you leave a contact method?
